<?php

namespace App\Models;

use Database\Factories\AiInteractionLogFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

#[Fillable([
    'user_id',
    'student_profile_id',
    'prompt_template_id',
    'engine_type',
    'model',
    'system_prompt',
    'user_prompt',
    'response_json',
    'response_raw',
    'input_tokens',
    'output_tokens',
    'cost_usd',
    'latency_ms',
    'is_success',
    'error_message',
    'called_at',
])]
class AiInteractionLog extends Model
{
    /** @use HasFactory<AiInteractionLogFactory> */
    use HasFactory;

    protected $table = 'ai_interaction_log';

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'response_json' => 'array',
            'is_success' => 'boolean',
            'called_at' => 'datetime',
        ];
    }

    /**
     * The user account associated with this AI call.
     *
     * Inverse belongs-to, nullable: null if the call was system-triggered
     * (e.g., weekly batch progress analysis).
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The student this AI call was made for.
     *
     * Inverse belongs-to, nullable: null for system-wide calls.
     */
    public function studentProfile(): BelongsTo
    {
        return $this->belongsTo(StudentProfile::class);
    }

    /**
     * The prompt template used for this AI call.
     *
     * Inverse belongs-to: traces which version of which prompt
     * produced this response, critical for prompt optimization.
     */
    public function promptTemplate(): BelongsTo
    {
        return $this->belongsTo(PromptTemplate::class);
    }

    /**
     * Question responses scored by this AI interaction.
     *
     * One-to-many: links individual answer evaluations back to the AI call.
     */
    public function questionResponses(): HasMany
    {
        return $this->hasMany(QuestionResponse::class, 'ai_interaction_id');
    }

    /**
     * Submission evaluations produced by this AI interaction.
     *
     * One-to-many: links essay evaluations back to the AI call.
     */
    public function submissionEvaluations(): HasMany
    {
        return $this->hasMany(SubmissionEvaluation::class, 'ai_interaction_id');
    }

    /**
     * Learning plans generated by this AI interaction.
     *
     * One-to-many: links plan generation back to the AI call.
     */
    public function learningPlans(): HasMany
    {
        return $this->hasMany(LearningPlan::class, 'ai_interaction_id');
    }

    /**
     * Progress snapshots analyzed by this AI interaction.
     *
     * One-to-many: links weekly progress analysis back to the AI call.
     */
    public function progressSnapshots(): HasMany
    {
        return $this->hasMany(ProgressSnapshot::class, 'ai_interaction_id');
    }

    /**
     * Diagnostic reports generated by this AI interaction.
     *
     * One-to-many: links placement test reports back to the AI call.
     */
    public function diagnosticReports(): HasMany
    {
        return $this->hasMany(DiagnosticReport::class, 'ai_interaction_id');
    }
}
